# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-25 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_external_clinic_cure1_external_clinic_cure2_external_clinic_cure3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_clinic_cure1',
            name='auth_doc',
            field=models.CharField(choices=[('محمد', 'محمد'), ('', ''), ('', ''), ('', ''), ('', '')], max_length=120, verbose_name='طبيب الشركة  '),
        ),
    ]
