# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-26 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_auto_20210225_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=120, verbose_name='Employee Name ')),
                ('department_number', models.CharField(max_length=120, verbose_name='Department Number ')),
                ('time_to_leave', models.DateTimeField(auto_now_add=True, null=True)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=120)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('request_status', models.CharField(max_length=120, verbose_name=' Status Of The Leave Request')),
                ('leave_reason', models.CharField(choices=[('Work', ' Work'), ('Emergency', 'Emergency')], max_length=120, verbose_name='Leaving For ... ')),
            ],
        ),
    ]
