# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-26 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_leave_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_requests',
            old_name='department_number',
            new_name='department_name',
        ),
        migrations.AddField(
            model_name='leave_requests',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('With return', ' With return'), ('No Return', 'No Return')], max_length=120, verbose_name='Leave Type '),
        ),
        migrations.AlterField(
            model_name='leave_requests',
            name='employee_name',
            field=models.ForeignKey(max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee Name '),
        ),
    ]
