# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-26 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_auto_20210226_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_requests',
            name='request_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leave_requests',
            name='time_to_leave',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
