# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-26 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_auto_20210226_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_requests',
            name='employee_name',
            field=models.CharField(max_length=120, null=True, verbose_name='Employee Name '),
        ),
    ]
