# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-02-27 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_auto_20210226_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_requests',
            name='request_revised',
            field=models.BooleanField(default=False),
        ),
    ]
